### ISSUE TITLE
Activateメッセージについて

### ISSUE THREAD

**Issue by HiroRittsu** [rionehome/spr#20]
# 相談

Activateメッセージの中のidを利用して遷移させていたが、JapanOpenからメッセージ名を用いて遷移先を決定する方式に変更になったため、わざわざActivateメッセージを利用するメリットが存在しなくなった。

もはやActivateメッセージが不要になったので、std_msgs::Stringに変更してもいいですかね...?

**Comment by nakano16180** [comment]
いいと思う。
独自メッセージはできるだけ避けるべきだし
